### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Tvarinsky** [SecHex/SecHex-Spoofy#121]
-

**Comment by sechexbackup** [comment]
Hey Tvarinsky, we didn't scam you. You're probably referring to the Discord server with the stolen vanity URL, right? .gg/sechex?

We already contacted Discord Support, but they don't seem to care about this kind of issue. However, feel free to message me on Discord. I might be able to share some collected information about the scammer with you.

My Discord tag: @sechex
The official server: https://discord.gg/bK7HMJvuRj

**Comment by Vuexec** [comment]
I got scammed too but I don't care because I'm rich 😂

Here's how it went down for anyone else, I paid for a spoofer, they said wait 1-2 hours, i said "why", the mong said "idk" LOL
then I @ed him and he said "sory i typed the wrong number it is 35euro not 25euro" LOOOOL then i said "refund please" I suspected it was a scam, the server is setup so shitly, I just wanted to see if I was right tbh, the paypal name he gave was Sylwia Adamczewska-Ignaciuk and currency was Polish złoty

A small tip to the creator to stop people from getting scammed and giving yourself a bad name, change the discord invite here and anywhere else

https://github.com/SecHex/SecHex-Spoofy?tab=readme-ov-file#contributors-%EF%B8%8F

<3

**Comment by sechexbackup** [comment]
They scam people but are unable to use a VPN or proxy.

@skr3l_
IP hashed: ed8456f0e435d6ea5d23fad83456b2e8
Browser: N/A
Locale: pl
2FA enabled: false
Country: PL
Region: Mazovia
ISP: AS12912 (T-Mobile Polska)

**Comment by Vuexec** [comment]
How did you get this info

**Comment by biggy-toothberg** [comment]
Had to delete the previous message first. I'm not unkind. The information comes from the verification system. The skids don’t even bother trying to scam people authentically, nor do they care about their own security. On YouTube and various forums, my stuff is also being "sold" or offered for download with malware. Just downright unpleasant.

**Comment by Vuexec** [comment]
So the code in this repo isnt malware?

**Comment by biggy-toothberg** [comment]
The code here on GitHub? Why would I try to push malware onto anyone? This project started out small and was originally just a private project. Besides, the code is publicly accessible, as is the malware analysis for the .dll.

**Comment by Vuexec** [comment]
I just have to ask because a lot of free HWID spoofers contain malware, you seem genuine

**Comment by biggy-toothberg** [comment]
All good. If you have any questions about the stuff, feel free to join the "original" Discord or hit up my DMs on DC. :)

**Comment by Vuexec** [comment]
<3 Whats the original discord, ANTIDOTE?

**Comment by biggy-toothberg** [comment]
Thats right.

**Comment by acebota** [comment]
skill issue
